[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask-caching==2.3.0",
    "flask-login==0.6.3",
    "flask-sqlalchemy==3.1.1",
    "flask-wtf==1.2.2",
    "flask==3.1.0",
    "poetry-lock-package==0.5.1",
]
